version: "2"

services:

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: free_php
    ports:
      - "9000:9000"
    volumes:
      - /mnt/docker_free/php/etc/:/usr/local/etc/
      - /mnt/docker_free/freeNovel/:/mnt/docker_free/freeNovel/
      - /mnt/docker_free/logs/php/:/var/log/php/
    restart: always
    privileged: true
 
  nginx:
    image: nginx:1.14.2-alpine
    container_name: free_nginx
    ports:
      - "80:80"
    volumes:
      - /mnt/docker_free/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/docker_free/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - /mnt/docker_free/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - /mnt/docker_free/nginx/client.conf:/etc/nginx/conf.d/client.conf
      - /mnt/docker_free/freeNovel/:/mnt/docker_free/freeNovel/
      - /mnt/docker_free/logs/nginx/:/var/log/nginx/
    restart: always
    privileged: true

  redis:
    image: redis:4.0.14-alpine
    container_name: free_redis
    ports:
      - "6379:6379"
    volumes:
      - /mnt/docker_free/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: always
    privileged: true


    