FROM php:deps

MAINTAINER szh <sali_hub@163.com>

ENV WORK_PATH /var/html/work
ENV PHPIZE_DEPS \
		autoconf \
		dpkg-dev dpkg \
		file \
		g++ \
		gcc \
		libc-dev \
		make \
		pkgconf \
		re2c

RUN mkdir -p $WORK_PATH

WORKDIR $WORK_PATH

ADD ./repo $WORK_PATH

RUN set -e && apk add $PHPIZE_DEPS \
&& tar -xf rabbitmq-c-0.8.0.tar.gz \
&& rm -rf rabbitmq-c-0.8.0.tar.gz \
&& cd rabbitmq-c-0.8.0 \
&& ./configure --prefix=/usr/local/rabbitmq-c-0.8.0 && make && make install \
&& cd ../ && rm -rf rabbitmq-c-0.8.0 

mkdir build 
cd build
cmake ..
make 
make install

#&& tar -xf amqp-1.9.4.tgz \
##&& cp /usr/local/rabbitmq-c-0.8.0/include/amqp_ssl_socket.h $WORK_PATH//amqp-1.9.4 \
#&& docker-php-ext-configure $WORK_PATH/amqp-1.9.4 --with-amqp --with-librabbitmq-dir=/usr/local/rabbitmq-c-0.8.0 \
#&& docker-php-ext-install $WORK_PATH/amqp-1.9.4 \
#&& rm -rf amqp-1.9.4 \
#&& apk del $PHPIZE_DEPS

CMD ["php-fpm"]